### PR TITLE
Fix importing deprecated alias in python>=3.10 (fixes #219)

### LINKED ISSUE #219: breaks with python3.10 due to deprecated (and now removed) use of collections.Callable
```
[...]
  File ".../venv/lib/python3.10/site-packages/Exscript/util/collections.py", line 9, in <module>
    from collections import OrderedDict, Callable, defaultdict
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Also see:
* https://docs.python.org/3/whatsnew/3.10.html#removed
* https://github.com/python/cpython/issues/81505

### PR DESCRIPTION
**Pull request by hennadii-demchenko**
Signed-off-by: Hennadii Demchenko <impskievua@gmail.com>

### CODE REVIEW

**Comment by hennadii-demchenko** [comment]
[knipknap](https://github.com/knipknap) I understand this repo hasn't been updated in a while, but can you look into this PR and merge it, 3.10 and above are becoming the new upstream version of python, and package refuses to work without this kind of fix.

**Comment by knipknap** [comment]
Looks good. Thank you!

**Comment by hennadii-demchenko** [comment]
@knipknap, is there a release planned, that will include this update?

**Comment by miaoxw** [comment]
I have the same question. Hope to see new version in PyPI soon!

**Comment by knipknap** [comment]
Done

**Pull request merged**
