### PR TITLE
Add driver for Arista EOS

### PR DESCRIPTION
**Pull request by souperrod**

### CODE REVIEW

**Comment by knipknap** [comment]
Thanks for the patch! Since i don't have a device to test with, could you also provide a test? This is easyly done by adding a simple text file here:

https://github.com/knipknap/exscript/tree/master/tests/Exscript/protocols/banners

**Comment by souperrod** [comment]
I've added a series of login processions/banners.

**Comment by knipknap** [comment]
Thanks, I will test later today.

**Comment by souperrod** [comment]
Thanks.  I saw you doing some other cleanup and closing out old/stale PRs.
Any chance you will also be posting an updated package on PyPI?  :-)

**Comment by knipknap** [comment]
Before the next release I want to remove unused parts of the module (src/Exscriptd and src/TkExscript) and move to a more standard module layout. But we have some dependencies that we need to remove first.

**Comment by egroeper** [comment]
@knipknap Great! I thought about this, too. But I was unsure, if that would be fine for you.
I think the cleanup makes supporting Python 3 a lot easier. Although there would still be a significant amount of work.

**Pull request merged**
