### PR TITLE
Add new driver for Riverbed RIOS (SteelHead)

### PR DESCRIPTION
**Pull request by maximumG**
Adding a new driver for Riverbed SteelHead running RIverbed OS (RIOS).

### CODE REVIEW

**Comment by maximumG** [comment]
Would it possible to accept this pull request ?

**Comment by maximumG** [comment]
Any updates on that feature branch ?

**Comment by egroeper** [comment]
This fails the OsGuesser Test:
```
FAIL: testDataReceived (protocols.OsGuesserTest.OsGuesserTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/groepeen/github/exscript/tests/Exscript/protocols/OsGuesserTest.py", line 71, in testDataReceived
    self.assertEqual(osg.get('os'), osname)
AssertionError: 'isam' != 'rios'

----------------------------------------------------------------------
```

I will need to think about how to handle this.

Best solution would be, if you could improve os detection either by matching against something more "special" in the banner (I don't see anything in your provided banner file) or by trying to match against something shown after login, that is somehow special to your device using check_response_for_os (I only found out about it just now).

You can always check the result of OsGuesserTest by using this command line:
```
python tests/Exscript/protocols/OsGuesserTest.py
```

Another solution would be to say, that this driver can only be chosen by manual selection. This would currently only work if you remove check_head_for_os and don't provide a banner file.
But it is a good idea to provide banner files. The whole driver testing stuff is the biggest problem I see currently. So I will need to adjust our testing code for this (to support manual selection drivers).

**Comment by egroeper** [comment]
> This would currently only work if you remove check_head_for_os and don't provide a banner file.
But it is a good idea to provide banner files.

You could simply rename rios.1 to .rios.1. Then it would be there for future use, but OsGuesserTest would ignore it.

**Comment by egroeper** [comment]
>> This would currently only work if you remove check_head_for_os and don't provide a banner file.
    But it is a good idea to provide banner files.

>You could simply rename rios.1 to .rios.1. Then it would be there for future use, but OsGuesserTest would ignore it.

I found a better solution. I will commit a fix for OsGuesserTest.
That way drivers not implementing check_head_for_os will not be tested against OsGuesser.

I will remove the check_head_for_os method and merge your driver.

Of course it would nevertheless be nice, if you see a way to support os guessing by implementing check_response_for_os.
This should support driver matching after authentication as long as no pre auth guesser yielded a confidence >= 80.

**Comment by egroeper** [comment]
Merged manually.

**Pull request closed without merging**
