### PR TITLE
Added driver for Adtran DSLAMs

### PR DESCRIPTION
**Pull request by lathspell**
Regarding https://github.com/knipknap/exscript/issues/168

### CODE REVIEW

**Comment by knipknap** [comment]
Awesome!
Could you make some minor fixes before I merge this?:
- The warnings from Hound above.
- Make sure that the driver is actually loaded in Exscript/protocols/drivers/__init__.py

**Comment by lathspell** [comment]
I've fixed the blank linkes but don't know how to "actually load" the driver in __init__.py. The file only contains "unused" imports and some reflection magic which I assumed to automatically add every imported class.

**Comment by knipknap** [comment]
Ah, sorry, I thought the "unused import" was in your driver, but this is from init.py... so everything was fine already.

**Comment by knipknap** [comment]
Thanks for the patch :-)

**Pull request merged**
